/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.myjava.java0402.ocp.lab20.game;

import javax.swing.ImageIcon;

/**
 *
 * @author student
 */
public class FightingJFrame extends javax.swing.JFrame {
    private static String path = "src\\main\\java\\com\\myjava\\java0402\\ocp\\lab20\\game\\fighting_images\\";
    private static ImageIcon[] images = {
        new ImageIcon(path+"ready_0.png"),
        new ImageIcon(path+"ready_1.png"),
        new ImageIcon(path+"ready_2.png"),
        new ImageIcon(path+"ready_3.png"),
        new ImageIcon(path+"ready_4.png"),
        new ImageIcon(path+"ready_5.png")
    };
     private static ImageIcon[] fight = {
        new ImageIcon(path+"fight_0.png"),
        new ImageIcon(path+"fight_1.png"),
        new ImageIcon(path+"fight_2.png"),
        new ImageIcon(path+"fight_3.png"),
        new ImageIcon(path+"fight_4.png"),
        new ImageIcon(path+"fight_5.png")
    };
    /**
     * Creates new form FightingJFrame
     */
    private  Ready r = new Ready();
    public FightingJFrame() {
        initComponents();
        r.start();
        
    }
    
    class Ready extends Thread{
        boolean isReady = true;
        
        
        @Override
        public void run() {
            for (int i =0;true;i++){
                if(isReady){
                    actor.setIcon(images[i%images.length]);
                    try {
                        Thread.sleep(100);
                    } catch (Exception e) {
                    }
                    if(i ==Integer.MAX_VALUE){
                        i =0;
                    }
                }else{
                    actor.setIcon(fight[i%fight.length]);
                    try {
                        Thread.sleep(100);
                    } catch (Exception e) {
                    }
                    if(i ==Integer.MAX_VALUE){
                        i =0;
                    }
                }
                
            }
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        actor = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addComponent(actor, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(453, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(actor, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(101, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
        if(evt.getClickCount() ==2){
            r.isReady = !r.isReady;//true 變false false 便true
        }
    }//GEN-LAST:event_formMouseClicked

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_formKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FightingJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FightingJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FightingJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FightingJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FightingJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel actor;
    // End of variables declaration//GEN-END:variables
}
